#
# YAML Config file for evmcmd
#

# Application config items
application:
   prompt: "evmcmd>"
   instpath: "./"

# Connection config items
connection:
   host: "192.168.1.72"
   port: "4443" # Use this in case the CFME engine is listening on another port
   user: "admin"
   pass: "smartvm"
